before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: tNAdA63jkK99zw7LE0dMboll3tWqcrdDOHy/P4x/8gX+Vok1p5LS9F/NnXEJyMqL4YqSL0hWiRQ2kMn1V6bh/5Iq6488KizV5qByVcvsU8DDFhJ1PQuKqGWrwxJvA3ru/0lL+9Y1ngJkS2CkG6iIKyWvc7l8rnS7NIKc6K2BNqUqjzonlrxNwerjBsnA5ac4vQgx4UVJ+2ZMPrXvK47GPb1uTV2MdnpyWCWjczi+vQ5QogNeiax9ycTwlZq+Vk3PpVRnhJWrE6/qS38rW3nRMIMTq2vm7YIvQ09yV5byEUYrHF8GBEZQHCGTLwpcK/NiX0xprD4WrFD5twcm2CyK4DN0hSrMiUoWLeivg0hCtKNQ+2+khjpq8xWGWyoYU3leUl5Uo2ZZpgFyS9JjhTQZtrnwvw0LTIFOgbqBck0uWT6ECW5xXFkRnNpOU2qhM/w8hyHrmIPyO8g2JHUS2q3RdNJOI6/d1OH7jpFSnLaMZcgXSRpfHkfFKq6NxyrMFfpfAAfmEJPuRG1okBuhoG97Y4CdmRgTWhuX2LU/X6iRQc+qcBK6CXLVYI+Y9TrBXc2x4D2el9yML25zSz83STfDOo/hTW9qzxMKeoRhJ1WXG9ewNcrXrXY/bXy1t4mmNlSnzPZ+shW1q4ezSwlFjzt6UrS002hstGV6LFdYs0w0Hwo= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
